"""
SLSA Provenance Generator

Generates SLSA (Supply-chain Levels for Software Artifacts) provenance metadata.

Targets SLSA Level 2:
- Provenance generation
- Build service identity
- Build integrity guarantees
"""

from typing import Dict, Any, List, Optional
from datetime import datetime
from pathlib import Path
import json
import hashlib
import platform
import os


class SLSAProvenanceGenerator:
    """
    Generate SLSA provenance for T.A.R.S. builds.

    SLSA Levels:
    - Level 1: Provenance exists
    - Level 2: Provenance generated by build service
    - Level 3: Build hardened against tampering
    """

    def __init__(
        self,
        project_name: str = "tars-observability",
        project_version: str = "1.0.2-dev",
        repository_url: str = "https://github.com/veleron-dev/tars",
    ):
        """
        Initialize SLSA provenance generator.

        Args:
            project_name: Project name
            project_version: Project version
            repository_url: Source repository URL
        """
        self.project_name = project_name
        self.project_version = project_version
        self.repository_url = repository_url

    def generate_provenance(
        self,
        artifact_path: Path,
        build_type: str = "python-wheel",
        builder_id: str = "https://github.com/veleron-dev/tars/actions",
        invocation_id: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Generate SLSA provenance v1.0.

        Args:
            artifact_path: Path to build artifact
            build_type: Type of build (python-wheel, docker-image, etc.)
            builder_id: Builder identity (CI/CD system)
            invocation_id: Unique build invocation ID

        Returns:
            SLSA provenance document
        """
        # Calculate artifact digest
        artifact_digest = self._calculate_sha256(artifact_path)

        # Build provenance
        provenance = {
            "_type": "https://in-toto.io/Statement/v1",
            "subject": [
                {
                    "name": artifact_path.name,
                    "digest": {
                        "sha256": artifact_digest,
                    }
                }
            ],
            "predicateType": "https://slsa.dev/provenance/v1",
            "predicate": {
                "buildDefinition": {
                    "buildType": f"https://tars.example.com/build-types/{build_type}",
                    "externalParameters": {
                        "repository": self.repository_url,
                        "ref": f"refs/tags/v{self.project_version}",
                        "version": self.project_version,
                    },
                    "internalParameters": {
                        "platform": platform.system(),
                        "architecture": platform.machine(),
                        "python_version": platform.python_version(),
                    },
                    "resolvedDependencies": self._get_dependencies(),
                },
                "runDetails": {
                    "builder": {
                        "id": builder_id,
                        "version": {
                            "tars-build-system": "1.0.2-dev"
                        }
                    },
                    "metadata": {
                        "invocationId": invocation_id or self._generate_invocation_id(),
                        "startedOn": datetime.utcnow().isoformat() + "Z",
                        "finishedOn": datetime.utcnow().isoformat() + "Z",
                    },
                    "byproducts": []
                }
            }
        }

        return provenance

    def save_provenance(
        self,
        provenance: Dict[str, Any],
        output_path: Path,
    ):
        """
        Save provenance to file.

        Args:
            provenance: SLSA provenance document
            output_path: Path to save provenance file
        """
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w") as f:
            json.dump(provenance, f, indent=2)

    def _calculate_sha256(self, file_path: Path) -> str:
        """Calculate SHA-256 hash of file."""
        sha256 = hashlib.sha256()
        with open(file_path, "rb") as f:
            for chunk in iter(lambda: f.read(8192), b""):
                sha256.update(chunk)
        return sha256.hexdigest()

    def _get_dependencies(self) -> List[Dict[str, Any]]:
        """
        Get resolved dependencies for build.

        Returns:
            List of dependency descriptors
        """
        # For now, reference SBOM
        # In full implementation, parse requirements.txt or lockfile
        return [
            {
                "uri": "pkg:pypi/requirements-dev.txt",
                "digest": {
                    "sha256": "placeholder"  # TODO: Calculate actual hash
                }
            }
        ]

    def _generate_invocation_id(self) -> str:
        """Generate unique invocation ID."""
        timestamp = datetime.utcnow().isoformat()
        data = f"{self.project_name}:{self.project_version}:{timestamp}".encode("utf-8")
        return hashlib.sha256(data).hexdigest()[:16]


def generate_slsa_provenance_for_tars(
    artifact_path: Path,
    output_path: Path,
    build_type: str = "python-wheel",
):
    """
    Generate SLSA provenance for T.A.R.S. artifact.

    Args:
        artifact_path: Path to build artifact
        output_path: Path to save provenance file
        build_type: Type of build
    """
    generator = SLSAProvenanceGenerator(
        project_name="tars-observability",
        project_version="1.0.2-dev",
    )

    provenance = generator.generate_provenance(
        artifact_path=artifact_path,
        build_type=build_type,
    )

    generator.save_provenance(provenance, output_path)
    print(f"Generated SLSA provenance: {output_path}")
