apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: remediationactions.aiops.tars
spec:
  group: aiops.tars
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - policyName
                - actionType
              properties:
                policyName:
                  type: string
                  description: "Name of the RemediationPolicy that triggered this action"
                actionType:
                  type: string
                  description: "Type of remediation action"
                params:
                  type: object
                  description: "Action parameters"
                  additionalProperties:
                    type: string
                triggeredBy:
                  type: string
                  description: "What triggered this action (alert, anomaly, webhook)"
                triggeredAt:
                  type: string
                  format: date-time
                  description: "When the action was triggered"
                dryRun:
                  type: boolean
                  description: "Whether this was a dry-run execution"
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum: [Pending, Running, Succeeded, Failed, Cancelled]
                  description: "Current phase of the action"
                startTime:
                  type: string
                  format: date-time
                  description: "When execution started"
                completionTime:
                  type: string
                  format: date-time
                  description: "When execution completed"
                result:
                  type: object
                  description: "Execution result details"
                  properties:
                    success:
                      type: boolean
                    message:
                      type: string
                    changes:
                      type: array
                      description: "List of changes made"
                      items:
                        type: object
                        properties:
                          resource:
                            type: string
                          action:
                            type: string
                          before:
                            type: string
                          after:
                            type: string
                    revertHint:
                      type: string
                      description: "How to revert this action"
                error:
                  type: string
                  description: "Error message if failed"
                logs:
                  type: array
                  description: "Execution logs"
                  items:
                    type: object
                    properties:
                      timestamp:
                        type: string
                        format: date-time
                      level:
                        type: string
                      message:
                        type: string
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: remediationactions
    singular: remediationaction
    kind: RemediationAction
    shortNames:
      - ra
      - raction
