# PostgreSQL Replica Configuration for US-West
# Read-only replica synchronized from US-East primary

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-replica-config
  namespace: tars
  labels:
    app: postgresql
    role: replica
    region: us-west
data:
  # Replica PostgreSQL configuration
  postgresql.conf: |
    # Connection Settings
    listen_addresses = '*'
    port = 5432
    max_connections = 200

    # Memory Settings
    shared_buffers = 1.5GB
    effective_cache_size = 4.5GB
    maintenance_work_mem = 384MB
    work_mem = 24MB
    wal_buffers = 16MB

    # Replica Settings
    hot_standby = on
    hot_standby_feedback = on
    wal_receiver_status_interval = 10s
    wal_retrieve_retry_interval = 5000ms
    max_standby_streaming_delay = 30s
    max_standby_archive_delay = 60s

    # Checkpoint Settings
    checkpoint_timeout = 10min
    checkpoint_completion_target = 0.9
    max_wal_size = 4GB
    min_wal_size = 1GB

    # Query Planning
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200

    # Parallel Query
    max_worker_processes = 3
    max_parallel_workers_per_gather = 2
    max_parallel_maintenance_workers = 2
    max_parallel_workers = 3

    # Logging
    log_destination = 'stderr'
    logging_collector = on
    log_directory = 'log'
    log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
    log_rotation_age = 1d
    log_rotation_size = 100MB
    log_min_duration_statement = 1000
    log_checkpoints = on
    log_connections = on
    log_disconnections = on
    log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '

    # Read-only enforcement
    default_transaction_read_only = on

  # pg_hba.conf - Client authentication
  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            md5
    host    all             all             ::1/128                 md5
    host    all             all             10.0.0.0/8              md5
    host    all             all             0.0.0.0/0               md5

  # recovery.conf for streaming replication
  recovery.conf: |
    standby_mode = 'on'
    primary_conninfo = 'host=postgres-primary.tars.svc.cluster.local port=5432 user=replicator password=${REPLICATION_PASSWORD} application_name=tars_replica_west'
    primary_slot_name = 'replica_west_slot'
    restore_command = 'cp /var/lib/postgresql/wal_archive/%f %p'
    recovery_target_timeline = 'latest'

  # Initialization script
  init-replica.sh: |
    #!/bin/bash
    set -e

    echo "Initializing replica database..."

    PGDATA="/var/lib/postgresql/data/pgdata"
    PRIMARY_HOST="postgres-primary.tars.svc.cluster.local"

    # Wait for primary to be available
    until pg_isready -h $PRIMARY_HOST -p 5432 -U replicator; do
        echo "Waiting for primary database..."
        sleep 5
    done

    # Check if data directory is empty
    if [ -z "$(ls -A $PGDATA)" ]; then
        echo "Performing base backup from primary..."

        # Perform base backup
        PGPASSWORD=${REPLICATION_PASSWORD} pg_basebackup \
            -h $PRIMARY_HOST \
            -D $PGDATA \
            -U replicator \
            -P \
            -v \
            -R \
            -X stream \
            -C \
            -S replica_west_slot

        echo "Base backup complete!"
    else
        echo "Data directory not empty, skipping base backup"
    fi

    # Set up recovery configuration
    cat > $PGDATA/standby.signal <<EOF
    # This file indicates that this is a standby server
    EOF

    # Copy recovery configuration
    if [ ! -f $PGDATA/postgresql.auto.conf ]; then
        cat > $PGDATA/postgresql.auto.conf <<EOF
    primary_conninfo = 'host=$PRIMARY_HOST port=5432 user=replicator password=${REPLICATION_PASSWORD} application_name=tars_replica_west'
    primary_slot_name = 'replica_west_slot'
    EOF
    fi

    echo "Replica initialization complete!"

  # Health check script
  health-check.sh: |
    #!/bin/bash

    # Check if PostgreSQL is running
    if ! pg_isready -U postgres; then
        exit 1
    fi

    # Check replication status
    REPLICATION_LAG=$(psql -U postgres -t -c "SELECT EXTRACT(EPOCH FROM (now() - pg_last_xact_replay_timestamp()));" 2>/dev/null | tr -d ' ')

    # Alert if replication lag > 60 seconds
    if [ -n "$REPLICATION_LAG" ] && [ "$REPLICATION_LAG" != "" ]; then
        if (( $(echo "$REPLICATION_LAG > 60" | bc -l) )); then
            echo "WARNING: Replication lag is ${REPLICATION_LAG}s"
            exit 1
        fi
    fi

    exit 0

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-replica
  namespace: tars
  labels:
    app: postgresql
    role: replica
    region: us-west
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
    - name: metrics
      port: 9187
      targetPort: 9187
      protocol: TCP
  selector:
    app: postgresql
    role: replica

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-replica
  namespace: tars
  labels:
    app: postgresql
    role: replica
    region: us-west
spec:
  serviceName: postgres-replica
  replicas: 2  # Two replicas for high availability
  selector:
    matchLabels:
      app: postgresql
      role: replica
  template:
    metadata:
      labels:
        app: postgresql
        role: replica
        region: us-west
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
    spec:
      nodeSelector:
        region: us-west

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - postgresql
              topologyKey: kubernetes.io/hostname

      initContainers:
        - name: init-replica
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent

          command:
            - /bin/bash
            - /scripts/init-replica.sh

          env:
            - name: REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: replication-password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: config
              mountPath: /scripts

      containers:
        - name: postgresql
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent

          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: replication-password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          resources:
            limits:
              cpu: 3000m
              memory: 6Gi
            requests:
              cpu: 1500m
              memory: 3Gi

          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: config
              mountPath: /etc/postgresql
            - name: wal-archive
              mountPath: /var/lib/postgresql/wal_archive

          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U postgres
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            exec:
              command:
                - /bin/bash
                - /scripts/health-check.sh
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

        # PostgreSQL Exporter for Prometheus
        - name: postgres-exporter
          image: prometheuscommunity/postgres-exporter:latest
          imagePullPolicy: IfNotPresent

          ports:
            - name: metrics
              containerPort: 9187
              protocol: TCP

          env:
            - name: DATA_SOURCE_NAME
              value: postgresql://postgres:$(POSTGRES_PASSWORD)@localhost:5432/tars?sslmode=disable
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password

          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi

      volumes:
        - name: config
          configMap:
            name: postgres-replica-config
            defaultMode: 0755

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: fast-ssd
        resources:
          requests:
            storage: 200Gi

    - metadata:
        name: wal-archive
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: fast-ssd
        resources:
          requests:
            storage: 50Gi

---
# Service for load balancing across replicas
apiVersion: v1
kind: Service
metadata:
  name: postgres-replica-readonly
  namespace: tars
  labels:
    app: postgresql
    role: replica
    region: us-west
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgresql
    role: replica

---
# ServiceMonitor for Prometheus
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-replica
  namespace: tars
  labels:
    app: postgresql
    role: replica
spec:
  selector:
    matchLabels:
      app: postgresql
      role: replica
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics

---
# PrometheusRule for replica-specific alerts
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: postgres-replica-alerts
  namespace: tars
  labels:
    app: postgresql
    role: replica
spec:
  groups:
    - name: postgres_replica_alerts
      interval: 30s
      rules:
        - alert: PostgreSQLReplicaDown
          expr: up{job="postgres-replica"} == 0
          for: 1m
          labels:
            severity: critical
            component: database
            region: us-west
          annotations:
            summary: "PostgreSQL replica is down"
            description: "PostgreSQL replica in us-west has been down for more than 1 minute"

        - alert: HighReplicationLag
          expr: |
            pg_replication_lag{job="postgres-replica"} > 60
          for: 5m
          labels:
            severity: warning
            component: database
            region: us-west
          annotations:
            summary: "High replication lag"
            description: "Replication lag is {{ $value }}s (threshold: 60s)"

        - alert: VeryHighReplicationLag
          expr: |
            pg_replication_lag{job="postgres-replica"} > 300
          for: 2m
          labels:
            severity: critical
            component: database
            region: us-west
          annotations:
            summary: "Very high replication lag"
            description: "Replication lag is {{ $value }}s (threshold: 300s)"

        - alert: ReplicationBroken
          expr: |
            pg_stat_replication_replica_count == 0
          for: 1m
          labels:
            severity: critical
            component: database
            region: us-west
          annotations:
            summary: "Replication is broken"
            description: "No active replication connections detected"
