# PostgreSQL Primary Configuration for US-East
# Optimized for high-availability and replication

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-primary-config
  namespace: tars
  labels:
    app: postgresql
    role: primary
    region: us-east
data:
  # Primary PostgreSQL configuration
  postgresql.conf: |
    # Connection Settings
    listen_addresses = '*'
    port = 5432
    max_connections = 200
    superuser_reserved_connections = 3

    # Memory Settings
    shared_buffers = 2GB
    effective_cache_size = 6GB
    maintenance_work_mem = 512MB
    work_mem = 32MB
    wal_buffers = 16MB

    # WAL Settings (Write-Ahead Logging)
    wal_level = replica
    wal_log_hints = on
    max_wal_senders = 10
    max_replication_slots = 10
    wal_keep_size = 1GB

    # Archive Settings
    archive_mode = on
    archive_command = 'test ! -f /var/lib/postgresql/wal_archive/%f && cp %p /var/lib/postgresql/wal_archive/%f'
    archive_timeout = 300

    # Replication Settings
    hot_standby = on
    hot_standby_feedback = on
    wal_receiver_status_interval = 10s
    wal_sender_timeout = 60s
    wal_receiver_timeout = 60s

    # Synchronous Replication
    synchronous_commit = remote_apply
    synchronous_standby_names = 'ANY 1 (postgres_replica_west)'

    # Checkpoint Settings
    checkpoint_timeout = 10min
    checkpoint_completion_target = 0.9
    max_wal_size = 4GB
    min_wal_size = 1GB

    # Query Planning
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200
    cpu_tuple_cost = 0.01
    cpu_index_tuple_cost = 0.005
    cpu_operator_cost = 0.0025

    # Parallel Query
    max_worker_processes = 4
    max_parallel_workers_per_gather = 2
    max_parallel_maintenance_workers = 2
    max_parallel_workers = 4

    # Autovacuum
    autovacuum = on
    autovacuum_max_workers = 3
    autovacuum_naptime = 1min
    autovacuum_vacuum_threshold = 50
    autovacuum_analyze_threshold = 50
    autovacuum_vacuum_scale_factor = 0.1
    autovacuum_analyze_scale_factor = 0.05

    # Logging
    log_destination = 'stderr'
    logging_collector = on
    log_directory = 'log'
    log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
    log_rotation_age = 1d
    log_rotation_size = 100MB
    log_min_duration_statement = 1000
    log_checkpoints = on
    log_connections = on
    log_disconnections = on
    log_duration = off
    log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '
    log_lock_waits = on
    log_statement = 'ddl'
    log_temp_files = 0
    log_autovacuum_min_duration = 0
    log_replication_commands = on

    # Statement Timeout
    statement_timeout = 30000  # 30 seconds

    # Locale
    lc_messages = 'en_US.UTF-8'
    lc_monetary = 'en_US.UTF-8'
    lc_numeric = 'en_US.UTF-8'
    lc_time = 'en_US.UTF-8'
    default_text_search_config = 'pg_catalog.english'

    # Shared Libraries
    shared_preload_libraries = 'pg_stat_statements'

  # pg_hba.conf - Client authentication
  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    # Local connections
    local   all             all                                     trust

    # IPv4 local connections
    host    all             all             127.0.0.1/32            md5

    # IPv6 local connections
    host    all             all             ::1/128                 md5

    # Kubernetes cluster connections
    host    all             all             10.0.0.0/8              md5

    # Replication connections from replica
    host    replication     replicator      10.0.0.0/8              md5
    host    replication     replicator      0.0.0.0/0               md5

    # Application connections
    host    tars            tars_user       10.0.0.0/8              md5
    host    all             all             0.0.0.0/0               md5

  # Initialization script
  init-replication.sh: |
    #!/bin/bash
    set -e

    echo "Initializing primary database for replication..."

    # Create replication user
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        -- Create replication user
        DO \$\$
        BEGIN
            IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'replicator') THEN
                CREATE ROLE replicator WITH REPLICATION PASSWORD '${REPLICATION_PASSWORD}' LOGIN;
            END IF;
        END
        \$\$;

        -- Grant necessary permissions
        GRANT USAGE ON SCHEMA public TO replicator;
        ALTER ROLE replicator WITH REPLICATION;

        -- Create replication slot for west region
        SELECT pg_create_physical_replication_slot('replica_west_slot')
        WHERE NOT EXISTS (
            SELECT 1 FROM pg_replication_slots WHERE slot_name = 'replica_west_slot'
        );

        -- Enable pg_stat_statements
        CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

        -- Create monitoring user
        DO \$\$
        BEGIN
            IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'monitoring') THEN
                CREATE ROLE monitoring WITH LOGIN PASSWORD '${MONITORING_PASSWORD}';
            END IF;
        END
        \$\$;

        GRANT pg_monitor TO monitoring;
    EOSQL

    echo "Replication setup complete!"

  # Backup script
  backup.sh: |
    #!/bin/bash
    set -e

    BACKUP_DIR="/var/lib/postgresql/backups"
    TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    BACKUP_FILE="backup_${TIMESTAMP}.sql.gz"

    echo "Starting backup at $(date)"

    # Create backup directory
    mkdir -p $BACKUP_DIR

    # Perform backup
    pg_dump -U postgres -Fc -Z 9 tars | gzip > "${BACKUP_DIR}/${BACKUP_FILE}"

    # Upload to S3 (requires AWS CLI)
    if command -v aws &> /dev/null; then
        aws s3 cp "${BACKUP_DIR}/${BACKUP_FILE}" "s3://tars-backups-east/postgres/${BACKUP_FILE}"
        echo "Backup uploaded to S3"
    fi

    # Clean old backups (keep last 30 days)
    find $BACKUP_DIR -name "backup_*.sql.gz" -mtime +30 -delete

    echo "Backup complete at $(date)"

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-primary
  namespace: tars
  labels:
    app: postgresql
    role: primary
    region: us-east
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
    - name: metrics
      port: 9187
      targetPort: 9187
      protocol: TCP
  selector:
    app: postgresql
    role: primary

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-primary
  namespace: tars
  labels:
    app: postgresql
    role: primary
    region: us-east
spec:
  serviceName: postgres-primary
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
      role: primary
  template:
    metadata:
      labels:
        app: postgresql
        role: primary
        region: us-east
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
    spec:
      nodeSelector:
        region: us-east

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - postgresql
              topologyKey: kubernetes.io/hostname

      containers:
        - name: postgresql
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent

          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP

          env:
            - name: POSTGRES_DB
              value: tars
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: replication-password
            - name: MONITORING_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: monitoring-password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          resources:
            limits:
              cpu: 4000m
              memory: 8Gi
            requests:
              cpu: 2000m
              memory: 4Gi

          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: config
              mountPath: /etc/postgresql
            - name: wal-archive
              mountPath: /var/lib/postgresql/wal_archive
            - name: backups
              mountPath: /var/lib/postgresql/backups

          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U postgres
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U postgres
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

        # PostgreSQL Exporter for Prometheus
        - name: postgres-exporter
          image: prometheuscommunity/postgres-exporter:latest
          imagePullPolicy: IfNotPresent

          ports:
            - name: metrics
              containerPort: 9187
              protocol: TCP

          env:
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: exporter-dsn

          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi

      volumes:
        - name: config
          configMap:
            name: postgres-primary-config

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: fast-ssd
        resources:
          requests:
            storage: 200Gi

    - metadata:
        name: wal-archive
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: fast-ssd
        resources:
          requests:
            storage: 50Gi

    - metadata:
        name: backups
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 100Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: tars
type: Opaque
stringData:
  username: postgres
  password: changeme_postgres_password
  replication-password: changeme_replication_password
  monitoring-password: changeme_monitoring_password
  exporter-dsn: postgresql://monitoring:changeme_monitoring_password@localhost:5432/tars?sslmode=disable

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: tars
  labels:
    app: postgresql
    component: backup
spec:
  schedule: "0 2 * * *"  # 2 AM daily
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: postgres:15-alpine
              command:
                - /bin/bash
                - /scripts/backup.sh
              env:
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-credentials
                      key: password
              volumeMounts:
                - name: backups
                  mountPath: /var/lib/postgresql/backups
                - name: config
                  mountPath: /scripts
          volumes:
            - name: backups
              persistentVolumeClaim:
                claimName: postgres-primary-backups-0
            - name: config
              configMap:
                name: postgres-primary-config
                defaultMode: 0755
